### ISSUE TITLE
As a first time user I should to be able to register a new account so that I can access the backend of the web application

### ISSUE THREAD

**Issue by tommyb23** [comp3540/pokemonhq#27]
# Login Page
* On the login page, I should see a "Create a new account" link under the login button.
* If I click on the link, I should be redirected to the signup page.

# Signup Page
* On the signup page, I should see a registration form and action buttons for submitting the form and for going back to the login page.
* If I click on the "Back" button, I should be directed to the login page.

# Form 
* The form will contain the following five fields: first name, last name, email, password and confirm password. 
* An asterisk next to the field title signifies that I must populate the field before submitting the form.
* If I click on "Submit", the form should attempt to submit.

# Form Submission (Failure) 
* The form will fail to submit if I do not fill out all required form fields, and error messages will appear under each field stating that they cannot be empty. (Frontend validation should be used for this)
* When I add text to the field that contains an error, the error will disappear.

# Form Submission (Success)
* Once all mandatory fields have been filled, I will be able to successfully submit the form.

# Data Validation 
* The data that I submit to the server must meet the following validation criteria: unique email address, password containing at least 8 characters and matching password/password confirmation.

# Data validation (Failure)
* If my form data does not meet the validation criteria, a new account will not be created and the validation errors will show up under the form fields that failed. 

# Data validation (Success)
* If my form data meets the validation criteria, my account should be created.
* I should be automatically signed in and redirected to the backend's homepage.

**Comment by nicholaspaun** [comment]
Remaining:
* Unit tests with jest
