### ISSUE TITLE
As a user with an account I should be able to login so I can access the website's backend

### ISSUE THREAD

**Issue by tommyb23** [comp3540/pokemonhq#28]
# Login Page
* The login page should be the main point of entry to the backend of the web application.

# Form
* I should see two text fields for entering my email and password. 
* I should see a "Submit" button for submitting the login form.
* I should see an asterisk next to "email " and "password", signifying that they are mandatory fields.
* Clicking the "Submit" button should attempt a form submission. 

# Form Submission (Failure)
* I should not be able to submit the form if I did not fill out the mandatory fields. (Frontend validation should be used for this).
* Error messages should show under the empty mandatory fields if I try to submit the form. 
* The error messages should disappear if I populate the empty fields.

# Form Submission (Success)
* I should be able to submit the form if all mandatory fields are populated.

# Data Validation 
* The email that I submit should be the email I used when registering a new account. 
* The password should be the most up-to-date one that is associated to my account. 
* The correct email/password combination should sign me in.

# Data Validation (Failure)
* If the email/password that I submitted don't match the system's records, I should not be signed in to the web app.
* An error message will show above the login form stating that I did not enter the correct credentials.
* I should be able to attempt multiple login submissions. 

# Data Validation (Success)
* If the email/password that I submitted match the system's records, I should be signed in and redirected to the web app's backend.

**Comment by nicholaspaun** [comment]
* Already have a log in component, just need backend.
